### ISSUE TITLE
Fix Contract Tests coverage command to only run non-GSN tests

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#100]
Currently running `yarn coverage` in the `contracts` folder causes a test failure with the following error message `Error: Invalid JSON RPC response: ""`. This is not observed when running `yarn test`. Need to resolve this issue and produce a valid coverage report.

**Comment by mds1** [comment]
Can we do this for `umbra-js` also in the same issue/PR?

**Comment by mds1** [comment]
Gave it a P2 since it should be a really quick fix, may as well knock it out

**Comment by mds1** [comment]
Pretty sure all GSN code is now removed, so closing this
