### ISSUE TITLE
Convert umbra-js tests to HardHat and add Coverage Report

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#104]
Currently the tests use OZ tests environment and don't produce coverage.

**Comment by mds1** [comment]
Hey @wildmolasses, it seems right now running `yarn test` from the root causes a failure in an umbra-js test, but running `yarn test` from within the umbra-js folder does not. See https://github.com/ScopeLift/umbra-protocol/pull/145#pullrequestreview-626370648

Do you mind see if that's still the case after doing the Hardhat refactor as part of this issue?
