### ISSUE TITLE
Research Analytics Options For Frontend

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#110]
Is it possible to add privacy-preserving analytics to the frontend? Google Analytics is certainly off the table. Are there any privacy preserving options? Perhaps [Goat Counter](https://www.goatcounter.com/) or [something similar](https://github.com/zgoat/goatcounter/blob/master/docs/sessions.markdown#existing-solutions)? Or should we leave all analytics off the frontend?

Primary goal is to understand where there is friction— i.e. are they dropping off in the setup flow, send flow, etc...

**Comment by apbendi** [comment]
Also look at [Fathom](https://usefathom.com/)

**Comment by apbendi** [comment]
Also checkout https://plausible.io/

**Comment by alexkeating** [comment]
This is what element uses https://matomo.org/

**Comment by mds1** [comment]
Another option may be https://arcx.money/
