### ISSUE TITLE
Generate Docs From Natspec Comments Via Docgen

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#116]

**Comment by mds1** [comment]
To clarify, this is for the contracts. For umbra-js, we have #166. Some options for auto-generating the contract docs:

- Hardhat plugin: https://github.com/ItsNickBarry/hardhat-docgen
- ArcherDAO script: https://github.com/archerdao/governance/blob/master/docify.js
- Soldoc, thought it hasn't been updated recently: https://github.com/HQ20/soldoc
- solidity-docgen (requires a lot of steup/config): https://github.com/OpenZeppelin/solidity-docgen
- Sourced from replies to this tweet: https://twitter.com/nicksdjohnson/status/1398102195204100096

**Comment by apbendi** [comment]
included in #141
