### ISSUE TITLE
Get Prettier To Run On Contracts Directory Automatically

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#126]
Currently the commit hook doesn't seem to run prettier on the contract directory.

**Comment by mds1** [comment]
Seems we never added the `precommit` script from https://github.com/ScopeLift/umbra-protocol/pull/102#issuecomment-793014375, so I'm just going to add that in #122 so we can close this

**Comment by mds1** [comment]
Closed by https://github.com/ScopeLift/umbra-protocol/pull/122
