### ISSUE TITLE
Prepare deploy script + contracts for deterministic deploy addresses

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#127]
Since we'll be deploying Umbra on mainnet, testnet, and probably L2s soon, it'd be great if they all shared the same address. There's a few ways to do this:

1. The original way: Deploy from an account that has a nonce of zero on each network, and all contracts will have the same address. Just would want to confirm this works the same for the OVM and that they didn't change the way CREATE computes the contract address

2. CREATE2: Use a deterministic deployer contract that's already deployed on each network (there's a few different ones for mainnet/testnet, not sure about L2s). This requires making sure there's no `msg.sender` usage in the constructor. The only issue here is that if we deploy on the OVM, I don't think this would work, since part of CREATE2 address computation is `keccak256(init_code)` and `init_code` will differ since opcodes differ. So this approach may be out

3. [Nick's method](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1820.md#deployment-method)

I think approach 1 is the easiest, in which case there's nothing we really need to do to prepare except fund a new address on all networks (and possibly mining a fun vanity address)

**Comment by apbendi** [comment]
Done via fresh accounts
