### ISSUE TITLE
Improve CNS "Reverse Lookup" Operation

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#129]
Currently we use a Graph query to find the first CNS name *owned* by an address, and show that in the receive table and the top-right corner for logged in users. This is not a great algorithm, as that domain might resolve to a different address than the one that owns it, or to no address at all.

A better algorithm to approximate reverse lookup would be: first find names owned by the address, then lookup where each resolves to. Return the first name that resolves to the same address, or nothing if none do.

**Comment by mds1** [comment]
We now outsource the lookup work to the Unstoppable Resolution library, so closing this
