### ISSUE TITLE
Remove bytecode functionality from umbra-js and export encryption prefix

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#13]
Once we confirm the new approach to meta-transactions works as planned we can remove the functionality of associating bytecode with an ENS address.

Additionally, the encryption prefix is currently hidden in the KeyPair class. This should be defined elsewhere and exported.

To do:
- [ ] Remove bytecode functionality
- [ ] Export prefix 
- [ ] Clean up all export of constants to ensure consistency

**Comment by apbendi** [comment]
I believe you ripped this out @mds1, or am I mistaken?

**Comment by mds1** [comment]
The bytecode functionality is still in there, so we should keep this issue open for now

**Comment by mds1** [comment]
This is now outdated, so closing this issue
