### ISSUE TITLE
Explore publishing umbra-js package

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#134]
Note: document process internally for future projects/updates

**Comment by wildmolasses** [comment]
Here are the requirements I'm looking at:

- minified js bundles w/ source maps
- includes typescript source files
- package can be published to npm from command line (auto-version, etc) via yarn script

am i missing anything?

**Comment by mds1** [comment]
As an alternative to CLI publishing, can also consider a github workflow that publishes on merge to master. Whichever is simpler is ok with me
