### ISSUE TITLE
Copy for website FAQ Page

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#140]

**Comment by mds1** [comment]
## Introduction

- What is Umbra?
- Can you walk me through an example?
- How does it work?
- How does Umbra compare to Tornado Cash and Aztec?

## Account Setup

- Is this step required?
- Should I use my own ENS/CNS name or an umbra.eth subdomain?
- Can my subdomain be revoked?

## Sending

- Why are only certain tokens available?
- When will the recipient receive their funds?
- Why is the maximum memo length so short?

## Receving

- What address are safe for withdrawing funds to?
- Why does it take so long to scan for my funds?
- When are my funds available to withdraw?

## Technical Details

- How does it work? (more details)
- What are spending and viewing keys?

## For Developers

- How can I build on top of Umbra?
- How can I receive a user's viewing key, but not their spending key?
- What are Hooks and how do I use them?
- What is the payload extension and how do I use it?

## Advanced Mode

- What is Advanced Mode?
- How do I send funds to a user by their address or public key?
- How can I access funds sent to an address I own?
- How can I scan just certain range of blocks?

**Comment by mds1** [comment]
Writing up answers here before adding them to the site: https://hackmd.io/@scopelift/BkWfbt_HO
