### ISSUE TITLE
Let users do Account Setup for any ENS address they own

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#149]
Currently this is limited to just the ENS name their wallet address reverse-resolves to

**Comment by apbendi** [comment]
Possible problem: user can own an ENS name but not resolve to the owner's account.

Example

0x01 owns somename.eth but resolves to 0x02. Sets up Umbra with 0x01, signing with that address to generate the stealth keys. Now:

* Regular transfers to somename.eth go to 0x02.
* Umbra transfers to somename.eth can only be withdrawn by 0x01

Possible mitigation: only show ENS names they own that also resolve to the current account (regardless of reverse resolution status).

**Comment by mds1** [comment]
Outdated since we switched to the StealthKeyRegistry
