### ISSUE TITLE
Detect non-ASCII names wherever ENS names are used and warn user

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#154]
Source tweet with more info [here](https://twitter.com/makoto_inoue/status/1379539978372403203).

Full OpenSea warning is:

> ⚠️ ATTENTION: This name contains non-ASCII characters as shown above. Please be aware that there are characters that look identical or very similar to English letters, especially characters from Cyrillic and Greek. Also, traditional Chinese characters can look identical or very similar to simplified variants. For more information, please see this [Wikipedia article](https://en.wikipedia.org/wiki/IDN_homograph_attack).

<img src="https://user-images.githubusercontent.com/17163988/113781407-83551300-96e5-11eb-92e6-9b41967b9fdc.png" width=500px />
<img src="https://user-images.githubusercontent.com/17163988/113781418-86e89a00-96e5-11eb-9eba-41e21758cd40.png" width=600px />

**Comment by thelostone-mc** [comment]
Would we want this in send function / would this have to be triggered within metamask @mds1 ? 
My assumption is that we would add it here: 
![image](https://user-images.githubusercontent.com/5358146/152341215-6f92470d-2ba6-4a9c-ae79-fe2df39efe96.png)

**Comment by mds1** [comment]
Ah nice find in MM! Yea I like the idea of just pulling in the code directly to keep dependencies down, and we can just link to the original sources (both MM and the package itself).

Agree the warning should be on the send page. I think ideally we'd use the q-input hint text to display a warning directly under the input field. If that's tricky cause the q-input error stuff gets in the way we can always just put it directly above the send button

[Here](https://github.com/ScopeLift/umbra-protocol/blob/dad4975df65fa4907ae006e01904d634405d3d1a/frontend/src/components/AccountReceiveTable.vue#L39) are the color codes we use for warnings, though it might be nice to pull them out as variables into `quasar.variables.sass`

@apbendi let me know if you have any other thoughts

**Comment by mds1** [comment]
Wonder if ensjs has a method for this now: https://github.com/ensdomains/ensjs-v3

**Comment by alexkeating** [comment]
I looked and it looks like ensjs uses [this](https://github.com/adraffy/ens-normalize.js/) library which has some confusable validation.
