### ISSUE TITLE
Allow Subdomain Users To Repeat Setup Flow Successfully

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#186]
Currently, if the owner of a subdomain completes the setup flow, then tries to repeat it, they'll be stopped at step three with this error:

<img width="1021" alt="Screen Shot 2021-05-20 at 10 13 34 AM" src="https://user-images.githubusercontent.com/1479802/118994977-c6e1a480-b954-11eb-94fd-a14f9f4510cc.png">

That's because the UI assumes that, for subdomains, the user needs to claim it via the registrar, and validates that the subdomain is available before allowing them to continue. This is correct for *new* subdomains, but not for ones the user already owns.

The UI should validate if the the current account is the owner of the subdomain. If they are, the UI should skip the claim step, and instead allow the user to

* Update to the stealthKeyResolver from the public resolver if necessary (it would be weird, but not impossible, if it was, as it would imply the user changed their subdomain resolver independently)
* Call `setStealthKeys` to publish the users keys

This is, in essence, the same flow used for a user of an existing, "normal" ENS name, so perhaps there is a way to short circuit subdomain detection at an earlier step and kick them into the "normal" ENS name flow instead, if the subdomain is already owned by the user? Just a thought.

**Comment by mds1** [comment]
Outdated since we switched to the StealthKeyRegistry
