### ISSUE TITLE
Provide a UI for users to transfer their stealth domains

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#187]
Users can transfer their `umbra.eth` subdomains like any other ENS name. If they transfer their domain without resetting their stealth keys, it could result in funds that are hard to withdraw from the standard UI, as the private keys generated by new owners address will not match the public keys published in the resolver.

To prevent this confusion, we should provide a first party UI for users to transfer their subdomains to other users, and it should first set their stealth keys to 0, then send them to a new user. The ENS multicall might be useful here for making this one transaction.

Thinking through this more, this same issue applies to regular domains as well. Given that, the feature probably does not need to be limited to just subdomains, but to any user with a configured ENS name.

**Comment by mds1** [comment]
Given that we now map addresses (instead of ENS names) to stealth keys, this can be closed
