### ISSUE TITLE
Wrong number of txs in description when updating keys on the stealth resolver

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#193]
If the user is already using the forwarding stealth resolver, and goes through setup again, they'll be told they're told there are two txs for them to sign when in this case there is only one. To determine this, check if the user's ENS resolver is already set to our `ForwardingStealthKeyResolver` instance

<img width="856" alt="Screen Shot 2021-05-27 at 5 36 26 PM" src="https://user-images.githubusercontent.com/1479802/119900155-1eae7b80-bf12-11eb-8182-2594eb95ee0d.png">

**Comment by mds1** [comment]
Outdated as we now use the StealthKeyRegistry instead of a custom ENS resolver
