### ISSUE TITLE
Make Setup process more robust and clear

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#195]
From a user in Telegram:

> Hey guys, just did the setup. When I got to the 3 tx step, the first 2 went through but the third threw an "unable to estimate gas error" on the page so was never prompted for the 3rd 'set stealth keys' tx. Pressing "publish keys" again ultimately worked, but it resent the 'set auth' and 'set resolver' txs that had already gone through.
>
> Would be nice if that step in the UI showed 3 check marks for each tx as they cleared and allowed you to resend at the stage you need.

We can apply this to regular ENS setup (3 transactions) and subdomain setup (2 transactions)

**Comment by apbendi** [comment]
First step here is probably further research into how users receive the setup process, either via analytics and/or user calls.

**Comment by mds1** [comment]
Outdated since we switched to the StealthKeyRegistry
