### ISSUE TITLE
Possible issue with CEX practical use case cited in README

### ISSUE THREAD

**Issue by aspiers** [ScopeLift/umbra-protocol#204]
Firstly, thanks a lot for this awesome project!

I am wondering about [this line of `README.md`](https://github.com/ScopeLift/umbra-protocol/blob/ba88313c2895bd98bb4f41f83c094cf7f51fe681/README.md#L70), which states:

> Bob uses Umbra to withdraw his 1,000 Dai each week. He only need provide an address to send it to. Obviously, it's best for him to use an address that's not tied to his identity. He usually chooses to send it straight to an exchange, where he sells it for fiat as needed.

Due to the mention of fiat, I'm assuming that "exchange" refers to a centralized exchange (CEX) such as Coinbase or Binance.

If Bob sends ETH (say) or some ERC-20 assets from `stealth1` to a CEX, and then later from `stealth2` to a CEX, typically the following holds:

- `stealth1` and `stealth2` have both sent assets to the same CEX deposit address
- This CEX deposit address is unique to Bob's CEX account (necessarily, since otherwise the CEX wouldn't know which of its users' accounts to credit with the deposit - because Ethereum doesn't support including some kind of per-transaction reference with ETH or ERC-20 transfers).

(I say "typically" because it's possible that the deposit address can change over time, but at least in the case of Binance, Coinbase, Bitstamp, and Bitpanda, it does not change regularly.)

If the CEX requires KYC and comes under sufficient pressure (e.g. from regulators), they could disclose the identity behind the CEX deposit address.  In this case, the stealth addresses *start* to look like they *could* be tied to Bob's identity.  As long as Alice continues to respect Bob's privacy, there is no public proof that `stealth1` and `stealth2` are owned by this same identity, so Bob still has plausible deniability that the payments came from different sources.  But nevertheless his privacy is starting to be weakened.

Let's review what Umbra has achieved in this scenario.  It has introduced potential for:

- Alice claiming that she paid two separate people Charlie and Colin
- Alice claiming that she doesn't know Bob
- Bob claiming that he was paid by two separate people Charlie and Colin
- Bob claiming that he doesn't know Alice

These claims are fairly plausible with only two stealth addresses.  However, if Alice makes 50 payments to Bob in this way, it significantly weakens the plausibility.  If investigators spotted all of these transactions, and did manage to obtain Bob's identity from the CEX, they would probably have strong evidence connecting Alice to Bob.

**Of course this is not a criticism of Umbra; it is a weakness of using any CEX which requires KYC.**  But given that it is the only example of a practical use of Umbra given in the README, I would suggest considering the following two actions:

1. Give another example which doesn't have a similar weakness
2. Tweak the wording of this example to clarify the privacy risks associated with using Umbra in combination with a CEX in this way.

Hope that is useful food for thought.  Thanks again!

**Comment by mds1** [comment]
Hey @aspiers! You are totally right on all of this. This is a great explanation of the downsides of withdrawing to a CEX, and I agree it would be useful to be more explicit about this in the README or the FAQ.

In regards to another example which doesn't have a similar weakness, we are in the process of integrating with [Tornado Cash](https://tornado.cash/) and will update the docs with info on that once the integration is complete. Once complete, this will make it easy to deposit funds directly from a stealth address into Torndao, which is a big privacy improvement over simply withdrawing to a CEX

**Comment by seresistvanandras** [comment]
Great observations by @aspiers! A few nitpicks or rather questions.
> Let's review what Umbra has achieved in this scenario. It has introduced the potential for:
> 
> * Alice claiming that she paid two separate people Charlie and Colin

Is this really true given the observation that Charlie and Colin, i.e., the two stealth addresses `stealth1` and `stealth2` deposited to the same CEX deposit address? Given this blockchain data, it should be enough for any blockchain analyst to conclude that Charlie and Colin are indeed the same person! What am I missing? See Section 5.1. [in this paper](http://fc20.ifca.ai/preproceedings/31.pdf) (Address clustering heuristics for Ethereum by Friedhelm Victor)!

> * Alice claiming that she doesn't know Bob

This holds for blockchain analysts but not from the point of view of the CEX. 
> * Bob claiming that he was paid by two separate people Charlie and Colin

This holds against blockchain analysts as well as the CEX. IMO, in this scenario, this is the real added value of Umbra, i.e., plausibly deny any relationship between Alice and him as you correctly identify this in your last bullet point.

> * Bob claiming that he doesn't know Alice

**Comment by aspiers** [comment]
[**@seresistvanandras**](https://github.com/seresistvanandras) commented on [July 31, 2021 11:33 AM](https://github.com/ScopeLift/umbra-protocol/issues/204#issuecomment-890327265 "2021-07-31T10:33:07Z - Replied by Github Reply Comments"):
> Great observations by [@aspiers](https://github.com/aspiers)! A few nitpicks or rather questions.
> 
> > Let's review what Umbra has achieved in this scenario. It has introduced the potential for:
> > 
> > *   Alice claiming that she paid two separate people Charlie and Colin
> 
> Is this really true given the observation that Charlie and Colin, i.e., the two stealth addresses `stealth1` and `stealth2` deposited to the same CEX deposit address?

Note I wrote that it has introduced the *potential* for Alice to make this claim, not that it gives her a cast-iron indisputable claim.

> Given this blockchain data, it should be enough for any blockchain analyst to conclude that Charlie and Colin are indeed the same person! What am I missing?

They can infer that is likely, but they cannot prove it beyond doubt, because anyone who knows Bob's CEX deposit address can send funds to it.  There is nothing stopping Bob sharing this address with anyone, or even announcing it publicly. 

> See Section 5.1. [in this paper](http://fc20.ifca.ai/preproceedings/31.pdf) (Address clustering heuristics for Ethereum by Friedhelm Victor)!

I haven't time to read this right now unfortunately, but the presence of the word "heuristics" in the title strongly suggests that the paper covers inference of likely associations between addresses rather than solid proofs.

> > *   Alice claiming that she doesn't know Bob
> 
> This holds for blockchain analysts but not from the point of view of the CEX.

I think it does for the reasons stated above - there is no solid proof that `stealth1` and `stealth2` are owned by the same person, only a suspicion (which can grow stronger with the appearance of further single-use addresses in between Alice and Bob's CEX deposit account).

> > *   Bob claiming that he was paid by two separate people Charlie and Colin
> 
> This holds against blockchain analysts as well as the CEX.

If you agree that the CEX could not deny this claim then I'm not sure why you would argue against the CEX's view of Alice's claim above.

> IMO, in this scenario, this is the real added value of Umbra, i.e., plausibly deny any relationship between Alice and him as you correctly identify this in your last bullet point.

Yes, it's plausible (albeit suspicious) if there are only 2 single-use stealth addresses in between Alice and Bob's CEX deposit account, but if there are more then it seems to me that the plausibility rapidly decreases.

**Comment by seresistvanandras** [comment]
Thanks for the clarifications! Indeed you're right in that Bob's CEX address could be known by others than Bob. I missed this possibility! Hence, any inference between the stealth addresses and Bob's CEX address is just heuristic.

**Comment by aspiers** [comment]
No worries, thanks for the good discussion! :grin:
