### ISSUE TITLE
Implement app / umbra-js changes to support new StealthKeyRegistry

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#226]
This issue will require changes to both the Umbra frontend and `umbra-js` to support the new StealthKeyRegistry system. The registry has been deployed to [rinkeby](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/deploy-history/registry-rinkeby-latest.json) and [mainnet](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/deploy-history/registry-mainnet-latest.json).

#### Legacy User Detection

- [x] Legacy users, i.e. user's who have already gone through the current ENS/CNS stealth key resolution process, should be detected and shown a banner or message across the top of the page.
- [x] It should show a message like, "We've upgraded our key resolution system. Please submit one transaction to update your configuration. You won't be able to receive Umbra transactions until you've done so." The message should be a link which takes them to the `/setup`. It can also have a "Learn More" link afterwards which takes them to a yet-to-be-written FAQ question about the upgrade.

#### Determining Prior Setup & Fetching Public Stealth Keys

- [x] Call the Registry's [stealthKeys](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/contracts/StealthKeyRegistry.sol#L169) view method, with the connected address, and check if the `spendingKey` and the `viewingKey` returned are non-zero. If either (or both, as is the case of normal usage) are zero, then assume the user has not completed setup
- [x] As long as both keys are non-zero, use the keys + prefixes returned as a given address' stealth keys

#### Setup Flow

- [x] The updated setup flow should have only two steps:
     1. Sign the message to generate public/private keypair
     2. Submit transaction to the Registry's [setStealthKeys](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/contracts/StealthKeyRegistry.sol#L70) method

#### Sending

- [x] The "Send" page should now accept a regular Ethereum address OR an ENS/CNS name
    - [x] Perform validation on the address (checksum)
- [x] If the user provides an ENS/CNS name, first resolve the name to an address
- [x] Take the address (directly provided or resolved) and use it to determine if this address has completed setup (as described above)
    - [x] If the user has not registered their stealth keys, notify the sender that this address has not yet configured Umbra
    - [x] If the user has registered their stealth keys, use them as dictated by the protocol to generate and encrypt the stealth address for this transaction
- [x] If the user has toggled "Advanced Mode" on, there should be a checkbox below the recipient input which says "Send using recipient's Ethereum public key".
     - [x] When selected, this should map to the existing advanced mode functionality that occurs when a user has advanced mode and supplies a normal Ethereum address. Namely, it should use the recovered public key from a past transaction from the supplied address to server as the spending & viewing keys for the stealth transaction.
     - [x] It might be nice to also include a "learn more" link next to this checkbox which takes the user to an appropriately modified version of [this faq](https://app.umbra.cash/faq#how-do-i-send-funds-to-a-user-by-their-address-or-public-key) question explaining what they're doing

#### umbra-js

- [x] The entire DomainService class can probably be deprecated and ultimately remove, but for the current version, we probably want to keep it in for the sake of detecting legacy users, as described above
- [ ] All the ens & cns util functions can be deprecated and ultimately removed in the same fashion
- [ ] The ForwardingStealthKeyResolver, ENSRegistry, and CNSRegistry ABI's can all be deprecated and ultimately removed.
- [x] The StealthKeyRegistry ABI will have to be added
- [x] A new class for interacting with the `StealthKeyRegistry` is probably warranted. This can be a pretty simple convenience wrapper around the ethers contract instance, with an escape hatch to access the underlying instance
- [x] The `lookupRecipient` function will have to be updated to remove usage of DomainService and switch to an instance of the new StealthKeyRegistry convenience class

**Comment by mds1** [comment]
Looks great overall. I think you're right that there isn't really much we can do to break this into independent features/chunks. Just a few small comments/questions:

>  It should show a message like, "We've upgraded our key resolution system. Please submit one transaction to update your configuration." 

I think the message should also mention that you will not be able to receive funds via Umbra until you submit the transaction to update your configuration.

>  It might be nice to also include a "learn more" link next to this checkbox which takes the user to an appropriately modified version of this faq question explaining what they're doing

We'll probably want to do a pass through all the FAQ questions as some will probably change. Should we create an issue for it?

>  The entire DomainService class can probably be deprecated and ultimately remove, but for the current version, we probably want to keep it in for the sake of detecting legacy users, as described above

How do we know once we can delete all the legacy code? Should we setup a system that checks if a user migrated? Or just say "6 months" (or whatever) and publicly and announce that in various channels

> A new class for interacting with the StealthKeyRegistry is probably warranted. This can be a pretty simple convenience wrapper around the ethers contract instance, with an escape hatch to access the underlying instance

Why do we want a class, instead of just calling methods on the contract instance? I can't think of anything we'd need to persist/reuse other than the contract instance

**Comment by apbendi** [comment]
> I think the message should also mention that you will not be able to receive funds via Umbra until you submit the transaction to update your configuration.

Agreed and updated.

> We'll probably want to do a pass through all the FAQ questions as some will probably change. Should we create an issue for it?

Good idea. Done with #229.

> How do we know once we can delete all the legacy code? Should we setup a system that checks if a user migrated? Or just say "6 months" (or whatever) and publicly and announce that in various channels

Good question. I favor keeping it simple and just choosing a date. 6 months after shipping & announcing seems reasonable to me.

> Why do we want a class, instead of just calling methods on the contract instance? I can't think of anything we'd need to persist/reuse other than the contract instance

I think it would be for convenience and abstraction for would be integrators, especially those who might not be using ethers.js and wouldn't want ethers implementation leaking into their app.

**Comment by mds1** [comment]
> Good question. I favor keeping it simple and just choosing a date. 6 months after shipping & announcing seems reasonable to me.

Works for me 👍️

> I think it would be for convenience and abstraction for would be integrators, especially those who might not be using ethers.js and wouldn't want ethers implementation leaking into their app.

Ah I see, I thought you meant within the app, not umbra-js. Makes sense!
