### ISSUE TITLE
feat: don't require user to connect wallet on the send form until they click the "send" button

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#235]
This way people can generate payment links without connecting a wallet, and it's just a better UX in general

**Comment by mds1** [comment]
Ah good point. So it will try to auto-connect if `last-wallet` is set in local storage, but if MetaMask is locked that's when you get that modal.

There should be a way to not try auto-connecting (i.e. don't show the "Login and Authorize Your Wallet" modal) if the wallet is locked, because that's how https://app.uniswap.org works—if you visit it with MetaMask unlocked, it automatically connects, and if MetaMask is locked it doesn't try to connect.

If we can get the same UX as Uniswap in that regard, that would be ideal

**Comment by apbendi** [comment]
Closed— see #242 for more details.
