### ISSUE TITLE
Remove dependence on GasNow

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#236]
GasNow is being shut down on October 15th at 16:00 UTC, but we use it in `frontend/src/utils/utils.ts`

Let's replace the GasNow API with a get request to https://api.txprice.com/`, which is a proxy to Blocknative's gas estimator that doesn't require an API key. We should use the 99% confidence result. 

Because this also requires updating ETH withdrawals to support EIP-1559, this is a bit more complex than just changing the API. To complete this issue:
- [ ] In `frontend/src/utils/utils.ts`, update the type definitions and `getGasPrice` method to use https://api.txprice.com/ https://github.com/ScopeLift/umbra-protocol/blob/31d2ae5747d7fed7aa3be24f8a3ae7696047a02c/frontend/src/utils/utils.ts#L35-L62
- [ ] The order of objects in the `estimatedPrices` field returned from the https://api.txprice.com/ is not guaranteed, so we can't just pull index 0 to get the 99% confidence, instead we must filter the array for where `confidence === 99`
- [ ] ~~Update the ETH withdrawal form to have "Max priority fee" and "Max fee" fields, both in gwei, instead of just a gas price field like we currently have~~: https://github.com/ScopeLift/umbra-protocol/blob/f6470e06dcd4b6607094708eda7f15dd5b338e28/frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue#L40
- [ ] ~~Update the ETH withdrawal execution method to specify `maxFeePerGas` and `maxPriorityFeePerGas` instead of `gasPrice`~~: https://github.com/ScopeLift/umbra-protocol/blob/f6470e06dcd4b6607094708eda7f15dd5b338e28/frontend/src/components/AccountReceiveTable.vue#L474

(Edited the above after the below discussion to reduce the scope of this issue)

**Comment by radchukd** [comment]
@mds1 
1.  I should display `maxFeePerGas` as _Transaction Fee_, right?
2. I shouldn't touch umbra's code, right? It needs some changes for EIP-1559.
https://github.com/ScopeLift/umbra-protocol/blob/21746ea8b4ff7e3e5fb22b04e465c2bdd8513638/umbra-js/src/classes/Umbra.ts#L208

**Comment by mds1** [comment]
> I should display maxFeePerGas as Transaction Fee, right?

Actually, after thinking about this more I think we should leave the UI as is and change the scope of this issue to be only removing reliance on GasNow. Let me explain my reasoning, and let me know if you disagree (@apbendi curious to hear your thoughts too)

So the typical way to handle EIP-1559 fees (type 2 transactions) is to show the user two input fields, where only one is used to generate the estimated transaction fee. MetaMask is a good reference here. For example in the screenshot below, `maxPriorityFeePerGas` is 1.5 and `maxFeePerGas` is 111.165 gwei. So the total fee estimate is 111.165 gwei * 21000 gas limit * 1e9 / 1e18 = 0.002334 ETH

<img src="https://user-images.githubusercontent.com/17163988/136715841-ebef30d4-fcc1-4950-afc2-829997fdc003.png" width=300px />

Using that format means any excess payment is kept by me (e.g. if basefee was cheaper than expected my transaction might only cost 0.002 ETH instead of 0.0023 ETH, and I'll have only spent 0.002 ETH on fees), which normally is great.

But these transactions are from single-use stealth addresses—if there's excess ETH because our transaction was cheaper than expected, it will sit there, stuck, forever. So, may as well give it to the miner to get your transaction mined a little bit faster, meaning we may as well stick with the original type 0 transactions.

An alternative (but equivalent) approach would be to upgrade to type 2 transactions, but only show the user a single `maxFeePerGas` field, and behind the scenes always set `maxFeePerGas` and `maxPriorityFeePerGas` to the same value. This has the effect of giving any excess fee (above the basefee) as tip to the miner. The rest of this comment below is only relevant if we want to go this route



> I shouldn't touch umbra's code, right? It needs some changes for EIP-1559.

Good point, yea this withdraw method will have to be updated too so the overrides can handle EIP-1559. Ideally we'd also add some corresponding tests to `Umbra.test.ts` that test different overrides and check the transaction receipt to make the sure fees used matched the input fees

Our ethers version used is from pre-EIP1559, so if we update the ethers version, then our `Overrides` type that we import from ethers will get updated. That type should look [like this](https://github.com/ethers-io/ethers.js/blob/68229ac0aff790b083717dc73cd84f38d32a3926/packages/contracts/src.ts/index.ts#L17-L25) once we update ethers, and currently it's missing the ` maxFeePerGas` and `maxPriorityFeePerGas` types (we don't care about access lists here, though those are also missing in our overrides type)

**Comment by radchukd** [comment]
@mds1 Is there really a point in allowing users to changes those fees then? They are given a chance to screw up. And since it is only a disposable address they wouldn't get a second chance.
If it was up to me, I would have left the fee uneditable with value for 99 confidence. If the fee is too high, the user can come back later (after the NFT drop) and withdraw then.
