### ISSUE TITLE
Clear Receive page component state when user switches wallets

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#237]
There's a minimum of two issues here:
1. If you enter a specific private key with advanced mode on, scan for funds, and change accounts, the `scanPrivateKeyLocal` variable is still defined with the manually specific private key. As a result, funds from that account are shown instead of the new account. This data should be cleared
2. If you enter start and end blocks with `startBlockLocal` and `endBlockLocal` those values are also persisted

To resolve this issue, options are:
1. Just reload the page when the user changes wallets. This is a little tricky because just reloading if `userAddress` changes gets you an infinite reload loop because `userAddress` is undefined when the app first loads, until the wallet is connected. Additionally, only reloading if the last userAddress is defined AND there is a new one doesn't currently work because in `wallet.ts` we call `resetState()` when the user changes wallets, so you really have oldAddress -> undefined -> newAddress, and can't distinguish between that type of "intermediate" `undefined` user address vs a true "no wallet connected yet" `undefined`
2. Add a `resetState()` method to `AccountReceive.vue` that runs any time `userAddress` changes to just reset all state in that component to their default values. This is probably the way to go and shouldn't be too difficult

**Comment by apbendi** [comment]
I think for now we should not store them in local storage. It might be nice to have these setting stick at some point. If we do that, it would need to be in a more accessible/discoverable "settings" page or something like that. As it stands, these features are hidden behind the advanced mode flag and not visible in the form after they're set. It'd be too easy to get into a situation where the user has no idea they're set but they're still applied.

**Comment by mds1** [comment]
Cool, so let's go that route

So @radchukd for this PR, the first set of changes you have in #243 are good, then if you could also just blow away everything related to saving the start/end block values in local storage (in the same PR) that would be perfect!
