### ISSUE TITLE
Fix message signature used to generate key

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#238]
The method used to generate a user's Umbra-specific keys can be found [here](https://github.com/ScopeLift/umbra-protocol/blob/f6470e06dcd4b6607094708eda7f15dd5b338e28/umbra-js/src/classes/Umbra.ts#L346-L399). In that method, we first try getting a signature using `eth_sign`. For wallets that don't implement `eth_sign`, we fallback to `personal_sign`.

For some wallets, like MetaMask and Status, ethers [special cases](https://github.com/ethers-io/ethers.js/blob/d3b7130ed6ec50b192eb7f33905eaa327d65eee2/packages/providers/src.ts/web3-provider.ts#L34-L39) them and automatically replaces calls to `eth_sign` with `personal_sign`. 

`eth_sign` was the original method, and it lets you sign an arbitrary hash which is dangerous, because you can trick users into e.g. signing transactions. `personal_sign` was eventually added, which adds a prefix of `\x19Ethereum Signed Message:\n32` to the message being signed

I don't see a reason to keep `eth_sign` implemented, as I don't think many wallets are even using it. So we should:
1. Default to `personal_sign`
2. Fallback to `eth_sign`, but add a prefix so the signatures generated by `eth_sign` and `personal_sign` still match
3. Verify the "new" signatures generated by MetaMask are what we'd expect

If anyone contacts us because this broke the app for them and they can't access their funds, we can add a special "fund recovery login" page that (1) signs with `eth_sign`, (2) lets you repeat account setup to ensure you're set in the future

**Comment by mds1** [comment]
#240 implemented (1), items (2) and (3) are what's left here

**Comment by garyghayrat** [comment]
@mds1 Just wanted to bump this, what do you think about the third point? Is this something we still have to address or can we close this?
