### ISSUE TITLE
Update Frontend to Use ChainId Aware Relayer

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#253]
The relayer API has been updated to support multiple chains in the same deployment via a `chainId` query parameter passed with every request. This means only 1 relayer instance is required for mainnet and rinkeby, and in the near future, other chains as well.

Currently, the frontend uses the chainId to decide which relayer endpoint to use. We need to update the app to use the same relayer endpoint, but include the `chainId` query parameter in its requests.

Somewhat confusingly, the updated relayer is now deployed to `https://rinkeby.api.umbra.cash/`. Despite the (now outdated) URL, this relayer should work for mainnet and rinkeby. During development of the frontend changes, we should point the app to this URL for all endpoints. When the frontend updates are ready, we will deploy the updated relayer to production and deploy the now updated frontend (with the correct URL) at the same time.

For detailed documentation of the updated relayer endpoints, see [this documentation](https://github.com/ScopeLift/umbra-api/blob/generalize-chain-id/ENDPOINTS.md)

One important note related to Polygon support has to do with the return value from [relay](https://github.com/ScopeLift/umbra-api/blob/generalize-chain-id/ENDPOINTS.md#tokenstokenaddrrelay) endpoint. As documented, it currently returns a hash for use with the ITX API, which we enable via a [proxy endpoint](https://github.com/ScopeLift/umbra-api/blob/generalize-chain-id/ENDPOINTS.md#statusitxhash).

I propose that when the chain is Polygon, which will not use ITX, the relay endpoint will instead return a regular polygon network transaction hash in this parameter. The frontend should know not to pass this hash to the ITX proxy, but instead to use it as a normal hash to get the status of the transaction.

**Comment by mds1** [comment]
Closed by https://github.com/ScopeLift/umbra-protocol/pull/251
