### ISSUE TITLE
Some Product advice

### ISSUE THREAD

**Issue by Alexliu007** [ScopeLift/umbra-protocol#256]
One suggestion, when withdrawing, I would like to be able to customize the withdrawal amount instead of the default address balance. A major reason for this is that I am concerned that someone will presume my associated address based on the amount transferred, so I will need to adjust the amount when I have to withdraw money.

The second suggestion is that for transfers to other addresses, is there a history provided? I think this is important for the user who wants to know which addresses I have made transfers to.

**Comment by garyghayrat** [comment]
Your second suggestion is covered by #263 , this is in our backlog.
Your first suggestion is not really possible because of how Umbra works, but we appreciate your input!
