### ISSUE TITLE
Umbra Scanning Bottleneck Possible Mitigations

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#266]
Meta issue to document possible mitigations to the bottleneck of announcement scanning:

- [x] Async w/ progress bar (notification when completed)
- [x] Parrallelization
- [ ] Rust based crypto
- [x] Only scanning blocks after when the user set their stealth keys
- [ ] Caching previously decrypted messages
- [x] Lazy loading in UI (show detected announcements as they're found rather than waiting for all of them)
- [ ] Sharding the receive table between withdrawn/non-withdrawn
- [ ] Optional server side scanning via viewing key

**Comment by mds1** [comment]
#377 is another possible mitigation but requires a new contract. We may want a new contract anyway to implement that + NFT support ([1](https://twitter.com/VitalikButerin/status/1556548617636556800), [2](https://ethresear.ch/t/erc721-extension-for-zk-snarks/13237/2))
