### ISSUE TITLE
chore: yarn lint failing

### ISSUE THREAD

**Issue by thelostone-mc** [ScopeLift/umbra-protocol#270]
#### Description 

Looks like there are issues in compiler version being used.
This raises cause of the line https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/.solhint.json#L6

`yarn lint`

![image](https://user-images.githubusercontent.com/5358146/149160135-654e04e1-3ba2-4a14-bef4-5ccea91b7729.png)

#### Possible Solutions

- Remove the compiler version (as it is not relevant) **OR**
- Increment  
  - the compiler version to 0.8.7
  - the contracts are updated to 0.8.7
- Do nothing and let the lint fail as contract upgrades aren't needed

**Comment by alexkeating** [comment]
I can take this on
