### ISSUE TITLE
Fix app so it works in Firefox

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#28]
Visiting https://ropsten.umbra.cash/ in Firefox just shows a white page and nothing loads. From the console:

```
SyntaxError: invalid regexp group vendor.129cec47.js:1:7
```

**Comment by mds1** [comment]
The app seems to work in Firefox when run locally for development, but the error above occurs for the deployed version at https://ropsten.umbra.cash. So something occurs during the minimization/build process that causes this

**Comment by apbendi** [comment]
@mds1 via Telegram:

> Matt Solomon | Floatify, [Jun 16, 2020 at 12:05:30 PM]:
Firefox v77 and older doesn't support lookbehinds in regex, so I suspect a package we use has a regex that gets minified to use lookbehinds
>
> https://caniuse.com/#feat=js-regexp-lookbehind

Confirmed that `ropsten.umbra.cash` loads without issue in v78-beta:

<img width="1270" alt="Screen Shot 2020-06-16 at 12 16 27 PM" src="https://user-images.githubusercontent.com/1479802/84800093-40e20e80-afcb-11ea-9cd8-0186d0ba8255.png">

I strongly suspect your theory is correct here @mds1, question is whether there is a simple build setting we can choose to polyfill this. If not, and compatibility would be painful, then perhaps we just let older version of Firefox age out, considering this version should be released soon 😅

**Comment by apbendi** [comment]
The app loads w/o issue in the latest stable release of Firefox. Any reason not to close this one out @mds1?

**Comment by mds1** [comment]
Just tested with using Firefox v78.0.2 and and can confirm it works
