### ISSUE TITLE
Separate Keypairs Used For Stealth Address Generation Vs. Announcement Encryption

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#29]
### Proposal

Using either two ENS Text records, or one longer ENS Text record that represents two concatenated messages, give users the ability to (optionally?) publish TWO public keys representing two distinct keypairs:

* `PKa` - Public Key A, used by the sender for generating a stealth address for the receiver
* `pka` - Private Key A, used by the receiver to generate the stealth addresses public key for withdrawal
* `PKb` - Public Key B, used by the sender for encrypting the announcement messages published on chain using ECDH
* `pkb` - Private Key B, used by the receiver for decrypting announcements published on chain to look for payments to stealth addresses they control

#### Reason 1: Safety

A receiver may choose to run a service that automatically scans announcements and alerts them to any payments to steal addresses they control. This would require keeping a private key "hot" in a service exposed to the internet.

By separating `PKa` and `PKb`, a scanning service would only need to key `pkb` "hot", and expose `pka` only when making withdrawals.

If the user's scanning service was hacked, or `pkb` was otherwise compromised, the user loses privacy, but not their funds.

#### Reason 2: Delegation

A receiver may choose to delegate the service described in `Reason 1` to a trusted third party. Said party would know the identity of receiver, but never have the ability to confiscate the user's funds.

Why would a user who values privacy enough to use Umbra be willing to delegate this service, and thus disclose their supposedly private transactions to a third party? There are many usecases where they wouldn't, but there may be some where they would.

Example: a crypto invoicing SaaS integrated with Umbra. As a business owner, I'm generally comfortable with my invoicing software provider knowing who I'm invoicing and in what amounts, however I'd be decidedly less comfortable with that information being completely public knowledge.

An invoicing service built with Umbra could retain `pkb` for their customers, scan all announcements on behalf of their users, and send email notifications when stealth payments are received. At the same time, the user remains in control of their funds, and the wider world would have no knowledge of the revenue the business was generating, or from whom.

**Comment by mds1** [comment]
Support for this was added in #60. Leaving this open as `protocol-WIP` until we finish using those keys in the rest of the send/receive flow

**Comment by mds1** [comment]
#90 implements this in the `Umbra` helper class of `umbra-js`. The last place to finish implementing this is the [new ENS resolver contract](https://github.com/ensdomains/resolvers/pull/40), so I'll leave this issue open until that aspect is implemented into this repo

**Comment by mds1** [comment]
#96 updated `umbra-js` to support this, so I'm going to close this issue
