### ISSUE TITLE
On send page, show balance of each token in the dropdown

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#294]
Each row in this dropdown should should the user's balance of that token

<img width="506" alt="image" src="https://user-images.githubusercontent.com/17163988/154497407-aed583b6-2692-4a5c-8d29-2839b0027d5c.png">

**Comment by mds1** [comment]
Yea david and I chatted earlier, IMO we should close this issue and focus on #378 instead due to some trickiness above that doesn't seem worthwhile

**Comment by davidlaprade** [comment]
In case we do decide to move forward with this issue, [this](https://github.com/ScopeLift/umbra-protocol/tree/show-token-balances-on-send-page-dropdown-fixes-%23294) is where I left off.

**Comment by davidlaprade** [comment]
FWIW, n=1, as I'm working on other send-page tickets, I kind of miss this feature now 😅

**Comment by apbendi** [comment]
I actually still think this feature would be nice but it's not worth if it's tricky and a lot of work, as it sounds it is. So I'd say leave it open but just move it to the Backlog category instead of To Do

**Comment by mds1** [comment]
@davidlaprade Do you remember what the trickiness here was? It sounds like this should be simple because we already have the balances in the wallet store, and I can't remember the details of why this isn't simple

**Comment by davidlaprade** [comment]
I think all I can remember is what's in this comment: https://github.com/ScopeLift/umbra-protocol/issues/294#issuecomment-1225946597
