### ISSUE TITLE
Determine ENS integration plan

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#3]
To do:

- [ ] Acquire an ENS domain. I think umbra.eth would be best, but we'd have to make an offer for it on [OpenSea](https://opensea.io/assets/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/106578806187450758505896232890745754422408667398940215312069652333347801272828). I'm not sure how long that process takes so we should probably start that soon. Alternatively, we could buy another domain that is available.
- [ ] Figure out best way to associate public key with an ENS subdomain, e.g. matt.umbra.eth should have a public key associated with it for the sender to read. It looks like web3 has `getPubKey` and `setPubKey` [methods](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-ens.html#getpubkey) that might be useful. It also seems that the ENS [PublicResolver](https://docs.ens.domains/contract-api-reference/publicresolver) implements EIP619 in order to resolve public keys. This PublicResolver contract also has [get and set public key functions](https://docs.ens.domains/contract-api-reference/publicresolver#get-public-key), which I assume are the same as the web3 functions (but I have not confirmed this)

**Comment by apbendi** [comment]
> Acquire an ENS domain. I think umbra.eth would be best, but we'd have to make an offer for it on OpenSea.

I think we're looking at this a little differently. Why do you see the need to have users register a specific subdomain for this?

>  Figure out best way to associate public key with an ENS subdomain, e.g. matt.umbra.eth should have a public key associated with it for the sender to read

What if we simply publish an ENS [Text Record](https://eips.ethereum.org/EIPS/eip-634) with a vendor specific umbra key, say `vnd.umbra-v0` or something similar.  Then the user could sign a standard message and publish the signature to the text record.

**Comment by mds1** [comment]
> I think we're looking at this a little differently. Why do you see the need to have users register a specific subdomain for this?

True, you are right that it can just be stored at your existing ENS name. I think I just defaulted to subdomains so users don't need to worry about whether or not they have an ENS name already. 

Perhaps to keep it simpler for now we just require user's to have an existing ENS name, and later we can add support for a "we'll give you a subdomain to use if you don't have one" type of thing

> What if we simply publish an ENS Text Record with a vendor specific umbra key, say vnd.umbra-v0 or something similar. Then the user could sign a standard message and publish the signature to the text record.

Text record would work too, so I'm not sure what the tradeoff is to consider here. Though I think it would be easier to publish the public key directly, instead of the signature? That way we don't need to recover the public key every time someone sends funds to that user

**Comment by mds1** [comment]
> Text record would work too, so I'm not sure what the tradeoff is to consider here. Though I think it would be easier to publish the public key directly, instead of the signature? That way we don't need to recover the public key every time someone sends funds to that user

Ah, just saw your reasoning for this in #4. That makes sense, and sounds good to me. Ok, so let's do a text record signature then with some standard message to sign

**Comment by apbendi** [comment]
> True, you are right that it can just be stored at your existing ENS name. I think I just defaulted to subdomains so users don't need to worry about whether or not they have an ENS name already.

This is a good idea, but I think it's something you would build at the application layer, as opposed to into the base protocol.

**Comment by mds1** [comment]
Currently we require users to purchase and configure their own domain name. Potential feature for later is to get a domain such as umbra.eth and handle registration and configuration of `<username>.umbra.eth` for users

**Comment by mds1** [comment]
Outdated—will create a new issue to track ENS integration plan
