### ISSUE TITLE
Setup GitHub Actions for lint/test CI on PRs and push to master

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#307]
- [ ] Running `yarn test` in root
- [ ] Running `yarn lint`

**Comment by mds1** [comment]
@apbendi On the branch for #293 I cleaned up the frontend/umbra-js lint errors/warnings. Seems there's also a lot in the contracts folder—if you could clean those up I can get the CI setup

**Comment by apbendi** [comment]
@mds1 So I think the majority, if not all, of those errors come from the deploy script, and they're TypeScript linting errors, i.e. about things being `any` types. In other words, it seems like the linter is treating js files like TypeScript files. Any idea how to resolve that?

**Comment by mds1** [comment]
You can probably add them to the exclude path array in the tsconfig file

**Comment by apbendi** [comment]
That would mean they're not linted at all, right? I wonder if there is a way to get them linted correctly as JavaScript files 🤔

**Comment by mds1** [comment]
You could also just change the file extensions to make them TS files and disable the TS-specific checks in those files. But otherwise I’m not sure offhand and would need to look into it, though maybe @wildmolasses knows
