### ISSUE TITLE
Improve Encryption Process

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#31]
### Problem

The current encryption process is as follows:
1. Generate a random 32-byte number
2. Using an ephemeral keypair, sender computes shared secret with the receiver via ECDH
3. Use the shared secret to encrypt the random number with AES-256-CBC, which outputs the MAC, IV, and ciphertext
4. Announce the ciphertext, MAC, IV, and ephemeral public key on chain through an event

Note that steps 2 and 3 are handled by the current library we are using for encryption, [eccrypto](https://github.com/bitchan/eccrypto).

The current encryption process is suboptimal for a few reasons:
- IV is logged with the event, but this is not necessary since the payload to encrypt and the encryption key are always random
- MAC is logged with the event, but this is not necessary since the blockchain provides protects data integrity and authenticity

These are currently required by the eccrypto library, and results in unnecessary computation and gas costs.

### Potential solutions

1. Generate random number with the existing process, but use the WebCrypto API to encrypt it with AES-256 using the ECDH shared secret. Would need to decide which AES-256 mode of operation to use (currently using CBC which is probably sufficient). On chain we'd announce the ephemeral public key and encrypted random number
2. Generate random number with the existing process, but encrypt it with XOR. On chain we'd announce the ephemeral public key and encrypted random number. Can also use ECB mode of operation
3. Used the shared secret from ECDH as the random number. On chain we'd only need to announce the ephemeral public key. 

When choosing a solution, factors to consider include:
1. Security
2. Computation and scanning cost 
3. Compatibility with #30 

### References

- [Tweet pointing out this issue](https://twitter.com/julianor/status/1266441668913442823)
- [Tweet suggesting XOR and ECB](https://twitter.com/julianor/status/1266456414391803909?s=20)
- [Tweet suggesting ECDH secret](https://twitter.com/nicksdjohnson/status/1266464073576660992?s=20)
- [bips/bip-0047.mediawiki at master · bitcoin/bips](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki#notification-transaction)

**Comment by apbendi** [comment]
Let's say we used XOR + ECB, but also had a set prefix at the beginning of our plaintext. Doesn't this weaken our security?

**Comment by seresistvanandras** [comment]
In the current parameter setting all three proposals are equivalent in terms of provided bit-security. All three relies on the security of the Computational Diffie-Hellman assumption in the secpk256k1 curve. More specifically even if in 1) the random number is encrypted with AES-256, its security bottleneck is breaking the ECDH over secp256k1 as it is easier to break than breaking AES-256. One would first break ECDH and get the shared secret. Once, the attacker obtained the shared secret can decrypt the random number. The same argument applies to proposal 2). Even if XOR would give 256-bit security, the shared secret is easier to recover than breaking the symmetric cipher. 

> 3. Used the shared secret from ECDH as the random number. On chain we'd only need to announce the ephemeral public key.

The third proposal assumes the Computational Diffie-Hellman assumption over secp256k1, therefore its provided security level is approximately 128-bit security. Even though, the third proposal is the most efficient in the number of logged elements, we can rule it out as it is not compatible with #30. 

All the other differences in terms of off-chain computation and decryption are negligible.

**Comment by mds1** [comment]
Encryption will be done with XOR since it is simple and does not weaken security in any way

**Comment by mds1** [comment]
Closed by #58
