### ISSUE TITLE
Mitigate Twist Attacks

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#32]
## Problem

From the link in the references section:

> ### Group structure and the small subgroup attack
> 
> The addition operation described above defines a [group structure](https://en.wikipedia.org/wiki/Group_(mathematics)) on the points of an elliptic curve. Suppose we have an elliptic curve where the corresponding group of points `E` has a [subgroup](https://en.wikipedia.org/wiki/Subgroup) `H` with few elements (say a few billion) and assume that the number of elements in the subgroup is a prime. The number of elements of a group is called the *order* of the group.
> 
> Suppose Bob has a private key `b` that Alice wishes to learn something about. She can take a point `P` in the subgroup `H` (this point is not a public key corresponding to any particular private key, but there is no way for Bob to know this) and tell Bob that this is her public key and can Bob please send an encrypted message to her.
> 
> Bob will compute what he thinks is a shared secret `Q = b*P`. He will use the data in `Q` to encrypt a message to Alice and send her the encrypted message `C`.
> 
> Since Alice knows that the point `Q` is in the group `H` (and `H` has a small number of elements) she can attempt to brute-force decrypt the message `C` with the points
> 
> ```
> P, 2*P, 3*P, 4*P, ...
> ```
> 
> etc until the decryption succeeds. Suppose the decryption succeeds at `k*P`. She then knows that `Q = k*P` and also `Q = b*P` so Alice has now learned that `k = b mod q`, where `q` is the number of elements (i.e. the order) of the subgroup `H`.
> 
> Thus Alice was able to get information about Bobs private key by giving him a maliciously chosen curve point.
> 
> This specific attack on Bobs private key will not work as described for the elliptic curve secp256k1 since the number of elements of the group is a prime number. By [Lagrange's Theorem](https://en.wikipedia.org/wiki/Lagrange's_theorem_(group_theory)) this means that there are no non-trivial subgroups to this group.
> 
> ### Twist attacks on secp256k1
> 
> We can make a slight modification to the small subgroup attack mentioned above by having Alice choose a point on a modified curve.
> 
> The way she does this is as follows: Instead of using the secp256k1 curve defined by
> 
> ```
> y^2 = x^3 + 7
> ```
> 
> she uses a curve with a different constant term, for instance the curve `E2` defined by
> 
> ```
> y^2 = x^3 + 2.
> ```
> 
> Unlike the original secp256k1 curve this new curve will have some small subgroups and Alice can pick a point `P` in one of them and give to Bob. Recall in our discussion on elliptic curve addition and multiplication that the algebraic operations of addition and multiplication are not actually using the constant term of the curve.
> 
> If Bob has a naive implementation of the elliptic curve multiplication (`Q = b*P`) that does not check if `P` is actually on the secp256k1 curve (which it isn't) then his software will instead perform the computation on the curve `E2`, and Alice can perform the small subgroup attack described above.

## Solutions

There are a few potential solutions, again copying from the link in the references section:

> ### Summary & mitigations
> 
> We've shown that if Bob has a problematic implementation of elliptic curve encryption using the curve secp256k1 then Alice can steal Bob's private key by giving him a number of maliciously chosen curve points and having Bob encrypt messages using those curve points.
> 
> For instance, using a simple Sage function like
> 
> ```
> def compute_shared_secret(myPrivateKey, theirPublicKey):
>     return (myPrivateKey * theirPublicKey)
> ```
> 
> will be susceptible to this attack. Also implementing the elliptic curve multiplication algebraically without first confirming that the point is on the correct curve will be vulnerable to the attack.
> 
> How can Bob protect himself? In order to protect against this attack one needs to make sure to not compute elliptic curve multiplication on another curve than secp256k1. We can do either of the following:
> 
> * Do a verification that the curve point we are about to multiply is actually on the correct curve, by verifying that the equation is fulfilled.
> * Require use of compressed public keys. These are curve points represented not by a pair of integers `(x, y)` but instead by the number `x` along with a one-bit value that allows us to compute the number `y` using the curve equation. This makes the public key shorter and since we need to use the curve equation to get the complete point we can be sure that we are not using a different curve.
> * Use a different curve for encryption like curve25519 which has a robust implementation that is not vulnerable to this attack.> 

## References
- [blog/secp256k1_twist_attacks.md at master · christianlundkvist/blog](https://github.com/christianlundkvist/blog/blob/master/2020_05_26_secp256k1_twist_attacks/secp256k1_twist_attacks.md)

**Comment by seresistvanandras** [comment]
I think the Twist Attack described in Christian's blog post is not applicable in the Umbra setting. Even if the message (random number in Umbra's case) is chosen by the attacker (sender in Umbra), the attacker encrypts the random number herself. In the Twist Attack, the attacker crucially needs ciphertexts coming from the victim, i.e. the victim (receiver in Umbra) should encrypt messages chosen by the attacker. Luckily, in Umbra, victim only needs to decrypt off-chain, so this attack is not applicable in this setting.  

TL,DR: in Umbra, the receiver does not encrypt any message chosen by the sender, hence the Twist Attack is mitigated.

**Comment by mds1** [comment]
@seresistvanandras I was actually thinking about this from the other perspective, where the receiver is the attacker and the sender is the victim. I believe an attack could work as follows:

1. The receiver (attacker) could publish a public key `P` associated with a curve that has a different constant term
2. The sender (victim) would use `P` to send the receiver funds. The generate a random number, compute the stealth address, and encrypt the random number. (Because `P` is not part of the secp256k1 curve, the sent funds would be inaccessible by the receiver)
3. Once the encrypted random number is published, the receiver could then perform the attack since the sender encrypted the random number using the receiver's public key

It's possible I may be missing something and this isn't feasible. But even if so, it is probably a good idea to verify that `P` is part of secp256k1 regardless, for an extra bit of assurance.

**Comment by seresistvanandras** [comment]
I see. Interesting! You're right, this is possible, but to launch this attack sender (and her wallet software) should be quite careless. In your description receiver will learn sender's private key modulo a small subgroup's order. This is not lethal, but obviously not nice either. If receiver wants to fully recover sender's private key, then she should update her public key accordingly to learn the remainder of sender's private key modulo the other small subgroup's order. For the attack to be successful the following conditions should hold simultaneously:

1. Sender sends multiple transactions to receiver.
2. For each transaction receiver updates her public key and places them into different small subgroups. If she has a transaction for each small subgroup then she can apply the Chinese Remainder Theorem to recover sender's private key. However, all the funds received at these crafted points will most likely not be redeemable as likely they're not points on the secp256k1 curve. That's the cost from the attacker (receiver) point of view.
3. Sender's wallet software does not check, whether receiver's address is a valid Ethereum address.

Since [stealth address generation and announcement encryption](https://github.com/ScopeLift/umbra-protocol/issues/29) needs to be separated anyway, to mitigate this attack vector random number could be even encrypted using symmetric crypto, like AES, where the key for the cipher would be the result of a (non-interactive) Diffie-Hellman key-exchange.

**Comment by mds1** [comment]
> 3. Sender's wallet software does not check, whether receiver's address is a valid Ethereum address.

Currently we do not check this, but because the recipient publishes their public key this is a straightforward check. I believe adding this check would be sufficient to mitigate this attack.

>  where the shared key for the cipher would be the result of a (non-interactive) Diffie-Hellman key-exchange, i.e. public keys are known anyway by both parties assuming both of them already sent an Ethereum transaction using that public key.

This is what we currently do, but with an ephemeral keypair for the sender, though the encryption process will likely change as described in #31. However, I'm not sure I understand how using ECDH for generating the shared key mitigates this attack?

**Comment by seresistvanandras** [comment]
What I wanted with ECDH is that once you have the shared secret you can use even asymmetric-crypto with that shared secret, e.g. AES. Random number would be encrypted with AES and then you don't need to worry about twist attacks and other pitfalls of ECC/secp256k1.

**Comment by mds1** [comment]
Since both (1) announcement events, and (2) ENS public keys both use compressed public keys, I believe this attack is mitigated so I'm closing this issue

@seresistvanandras Feel free to reopen if you disagree 🙂
