### ISSUE TITLE
Friction for advanced mode

### ISSUE THREAD

**Issue by garyghayrat** [ScopeLift/umbra-protocol#362]
- Make sending using recipient's standard public key in advanced mode harder

Ideas:
1. When user checks the checkbox, have a pop-up warning to make sure users understand.
2. Another pop-up when user clicks Send.
3. Any other ideas?

**Comment by mds1** [comment]
Related to 1 and 2, one idea is ensure the warning text makes it clear that if you mess up while using advanced mode funds may be unrecoverable, i.e. make sure the warning is scary 😅

**Comment by alexkeating** [comment]
I will also pick this one up this week
