### ISSUE TITLE
Sending max balance

### ISSUE THREAD

**Issue by garyghayrat** [ScopeLift/umbra-protocol#363]
On the send page, let users click a 'Max' button to send max balance of selected token.
- Might be tricky with ETH because you need to estimate amount for gas.

**Comment by mds1** [comment]
We have a method called [`getEthSweepGasInfo `](https://github.com/ScopeLift/umbra-protocol/blob/72eee76c4f17f88aac2b88371bc408ff0452416a/umbra-js/src/utils/utils.ts#L338) that we use on the withdraw page to sweep all ETH from a stealth address. We should be able to use this same method on the send side.

**Comment by mds1** [comment]
Closed by #375, the native token sweeps are being tracked in #378
