### ISSUE TITLE
No RPC Url available for chainId: 42161 using `walletconnect`

### ISSUE THREAD

**Issue by Soptq** [ScopeLift/umbra-protocol#384]
Using `walletconnect` on arbitrum causing errors: No RPC Url available for chainId: 42161.

Context (in discord `help` channel): https://discord.com/channels/925416137225830450/925428183707287602/1013506343828725780

**Comment by alexkeating** [comment]
I will work on this one

**Comment by alexkeating** [comment]
Closed with #395
