### ISSUE TITLE
Max Button Should Be Inside Input On Mobile

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#398]
In normal desktop mode, the "Max" button on the send screen appears inside the Amount input:

<img width="300" alt="Screen Shot 2022-10-04 at 2 34 48 PM" src="https://user-images.githubusercontent.com/1479802/193909038-157f1329-26e9-42b2-8007-431e720c2d5d.png">

However in the mobile layout, it appears as a separate button outside the input:

<img width="300" alt="Screen Shot 2022-10-04 at 2 34 42 PM" src="https://user-images.githubusercontent.com/1479802/193909145-f0001710-4dfa-4deb-9a2c-31e7f95eaa2f.png">

I think the Max button should remain inside the input even in mobile mode. It's a small button and should be easy enough to tap even in a smaller context. Having a it as a separate button could create some UX confusion between "Max" and "Send".

**Comment by saimaheshtaduri** [comment]
I can fix this. assign to me @apbendi

**Comment by mds1** [comment]
Thanks! Just assigned it to you, let me know if you have any questions:)

**Comment by garyghayrat** [comment]
@saimaheshtaduri Hi, are there any updates on this issue?

**Comment by mds1** [comment]
@saimaheshtaduri I've unassigned you since we haven't heard back, but if you still want to work on this let us know
