### ISSUE TITLE
Determine how to get a user's public key

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#4]
We can ask a user to sign a message and recover their public key from that, but I'm not sure if there's a simpler way.  It would be convenient if web3 providers exposed the public key directly but I don't think they do

**Comment by apbendi** [comment]
> We can ask a user to sign a message and recover their public key from that, but I'm not sure if there's a simpler way.

Yes, I think rather than simply having the user publish their public key, we should have them publish a signed message and recover their key from it. This provides some extra assurance, as it proves the user was able to sign the message, avoiding things like typo-ing a public key when publishing.

**Comment by mds1** [comment]
> Yes, I think rather than simply having the user publish their public key, we should have them publish a signed message and recover their key from it.

This is currently implemented, so this can be closed
