### ISSUE TITLE
Get Network Switching Working With WalletConnect Once Supported

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#404]
Currently you can't switch network inside the app when connected with WalletConnect. This is because [Onboard does not support it](https://github.com/ScopeLift/umbra-protocol/pull/395#discussion_r990585307). We've requested this support from Onboard and should make sure it works with Umbra if/when implemented. If Onboard declines to implement it, we should investigate alternative ways to get it working.

https://github.com/blocknative/web3-onboard/issues/1313

**Comment by alexkeating** [comment]
I am going to spend a little bit of time on the onboard side seeing if we can resolve it as it doesn't seem like they have time to address this anytime soon.

**Comment by alexkeating** [comment]
Opened a pr for this https://github.com/blocknative/web3-onboard/pull/1351 and tested with Umbra locally and it seemed to be working.

**Comment by alexkeating** [comment]
I tried updating to the most recent version of web3 onboard wallet connect and ran into issues switching chains using our network dropdown. I left a comment on web3-onboard and will continue to look into why this is happening.

**Comment by mds1** [comment]
@alexkeating can you take a quick look at this? I imagine it should be supported by now. If it seems complex / not a quick fix I'll defer to @apbendi for priority

**Comment by alexkeating** [comment]
Tested and working this can be closed
