### ISSUE TITLE
bug: translations are not working for web3-onboard connection modal

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#449]
> Our i18n translations for Onboard are no longer working when Chinese is selected. Not sure if they dropped support or an update borked it. Mind taking a look? @alexkeating
> 
![image](https://user-images.githubusercontent.com/17163988/217038330-d074c347-33a4-4583-ad78-769541273f62.png)

_Originally posted by @garyghayrat in https://github.com/ScopeLift/umbra-protocol/issues/418#issuecomment-1337887554_

@garyghayrat @alexkeating not sure which of you is a better fit for this one, feel free to self-assign

**Comment by alexkeating** [comment]
Just tested this locally, and it is not working. From their docs it still seems like they support the translation object. I tried upgrading the packages and that did not help. I will make an issue tomorrow morning and see what they think
