### ISSUE TITLE
Determine how to manage public keys on ENS

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#45]
Questions/considerations:
- Should we store signatures or directly store public keys?
- Should they be stored as text records, or in dedicated record types?
- Make sure the approach is compatible #29 
- How should the issuing of subdomains be handled, to ensure we do not have the ability to pull them away from users?

**Comment by mds1** [comment]
Approach for items 1-3 above:
- Create a new resolver contract that stores two signatures in binary to minimize gas costs (see [EIP-1577](https://eips.ethereum.org/EIPS/eip-1577))
- To support users who already have existing ENS names, they can either:
    - Create an umbra-specific subdomain to point to this resolver
    - Migrate to the new resolver using the `setResolver` function on ENS registry—ideally in this case the new resolver would fall back to the public resolver

Approach for item 4 above:
- New users can be assigned a new subdomain of the root Umbra ENS name upon sign up
- Transfer ownership of the root Umbra ENS name to a new contract which can assign names but not reassign names
- Can transfer the registrant address to the zero address, which allows subdomains to still be assigned but prevents changing the controller address and transferring the registration

**Comment by apbendi** [comment]
The approach we'll be taking, with support from @Arachnid from ENS is as follows:

* A new resolver contract that stores the x-coordinate of two separate public keys, without the identifier bit, as binary data to minimize gas fees— possibly storing them as one field— and falls back to the public resolver for all other purposes.
* A contract for an Umbra subdomain which allows users to claim names, but does not allow names to be reassigned.
* On-chain components— if any are needed— for allowing users to enable Umbra support for existing ENS names that are currently using the public resolver, presumably by switching to the Umbra resolver.
*Note: The naming for the aforementioned keys should be 'generationPubKey' and 'encryptionPubKey'.

**Comment by Arachnid** [comment]
https://github.com/ensdomains/resolvers/pull/40

**Comment by apbendi** [comment]
Thanks @Arachnid, this is awesome! Appreciate you taking the time to make progress on this :)

A few quick questions:

* Can you help elucidate your choice of two `uint256` params for the keys? Since we're using 128 bit keys, could we get away with one slot instead of two? (possibly with the setter/getter as two keys for dev convenience)
* That's awesome these subdomain registrar contracts exist! Any idea when they'll be officially ready to go? Any docs on how to use them? Also, just out of curiosity, I'm wondering if you had any plans to get them audited?

Thanks again for the help so far! This will be great.

**Comment by Arachnid** [comment]
> So I guess my only question here is why uint256 vs. bytes32?

As curve coordinates they are integers, aren't they?

> That's awesome these subdomain registrar contracts exist! Any idea when they'll be officially ready to go? Any docs on how to use them? Also, just out of curiosity, I'm wondering if you had any plans to get them audited?

Jeff is currently working on something else, but will be back to work on them soon. We hope to have them done in the next month to 6 weeks. I would like to get them audited - particularly the wrapper contract - if we can find someone who can do so!

**Comment by apbendi** [comment]
Closed with https://github.com/ensdomains/resolvers/pull/41
