### ISSUE TITLE
Switching to any network other than Mainnet w/ network selector is broken

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#489]
In production, switching from one network to another using the app based network selector is broken, unless the destination network is mainnet. It produces the following error in console:

```
{
    "code": -32603,
    "message": "networkConfigurationId undefined does not match a configured networkConfiguration",
    "data": {
        "originalError": {}
    }
}
```

**Comment by alexkeating** [comment]
I think this is on the metamask side

**Comment by alexkeating** [comment]
This is working for me now and I think can be closed.

**Comment by apbendi** [comment]
Same here, and agreed. Closing!
