### ISSUE TITLE
Determine how to get a user's private key

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#5]
The frontend of the app needs access to the recipient's private key in order to compute the new private key used to access their funds. One option is to ask the user to manually copy and paste the private key from MetaMask, but it would be nice if there's a more user-friendly method.

**Comment by apbendi** [comment]
I think there is an underlying assumption here that the Public/Private keypair used for Umbra will be the same public/private keypair used for the user's address. Should we definitely do it this way?

There is an obvious pro for doing it this way: the user does not have to generate and manage another private key. Any other pros for this option?

Here are some cons I see:

* Using Umbra adds additional risk to your base account. If you have to trust your private key to Umbra (and any apps using it) you now risk your base account. If there is a bug in Umbra that leaks key material your entire account is compromised.
* Not compatible with contract accounts. The user might be using a smart wallet or might simply want to associate an Umbra keypair with a contract they control. This would not be possible if Umbra requires an EOA.

What do you think? Am I missing any pro/cons here?

**Comment by apbendi** [comment]
Even if Umbra generates the private key, we still have to securely manage storing it somewhere. One option would be to encrypt it using a `pbkdf` and store it in local storage. I'm guessing this is what extensions like MetaMask do.

Speaking of MetaMask, another option might be to write a Snap. I don't know if Snaps let you store sensitive encrypted material, but if they do, this could be helpful.

Regardless of how we want to handle this in the ultimate UI, I think it should be separate from the library here. The library should simply provide classes/functions that can be instantiated or used with keys.

Perhaps if we go the  `pbkdf` -> local storage route, we can provide some helper functions for that. Also, another thought: do we want to support public keys derived from mnemonic seeds? This would allow users to back up their Umbra key in the same way they're used to with their accounts.

**Comment by mds1** [comment]
> Using Umbra adds additional risk to your base account. If you have to trust your private key to Umbra (and any apps using it) you now risk your base account. If there is a bug in Umbra that leaks key material your entire account is compromised.

This might actually be a good argument in favor of only using ENS subdomains. If we ignore other wallets and assume many people use MetaMask (which I suspect will be true for many of the first users), you can just generate a new MetaMask address with its own private key, and we can use the GSN so user's don't need any ETH for gas. This prevents adding any risk to other existing accounts, since the private key is only associated with this "umbra only" MetaMask account and ENS address

> Not compatible with contract accounts. The user might be using a smart wallet or might simply want to associate an Umbra keypair with a contract they control. This would not be possible if Umbra requires an EOA.

Good point about contract wallets. But given that access to the umbra "receive" address is based on multiplying an EOA private key with some random value, I don't see how we can easily support the range of contract wallets. 

Contract wallets also are not very popular yet, so I think it's ok to worry about supporting them later.

**Comment by mds1** [comment]
> Even if Umbra generates the private key, we still have to securely manage storing it somewhere. One option would be to encrypt it using a pbkdf and store it in local storage. I'm guessing this is what extensions like MetaMask do.
>
> Speaking of MetaMask, another option might be to write a Snap. I don't know if Snaps let you store sensitive encrypted material, but if they do, this could be helpful.

Interesting thought about Snaps, that could be useful. I'm not too familiar with them but will have to look into those.

I once used [this article](https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data) to recover my seed phrase manually, which gives some insight into how MetaMask stores your seed phrase

> Regardless of how we want to handle this in the ultimate UI, I think it should be separate from the library here. The library should simply provide classes/functions that can be instantiated or used with keys.
>
> Perhaps if we go the pbkdf -> local storage route, we can provide some helper functions for that. Also, another thought: do we want to support public keys derived from mnemonic seeds? This would allow users to back up their Umbra key in the same way they're used to with their accounts.

Yea that seems like a good architecture. Perhaps we should rename this repo to umbra-protocol and create a separate repo for the app itself to move these issues into. And then once we decide on a key-management approach add some helper functions to this repo.

I think we should try to avoid users needing a separate mnemonic just for Umbra, and that we'd want to support something like MetaMask integration, where they already have a single seed phrase backed up, and just use a new, separate keypair for Umbra

**Comment by apbendi** [comment]
> Good point about contract wallets. But given that access to the umbra "receive" address is based on multiplying an EOA private key with some random value, I don't see how we can easily support the range of contract wallets.

I meant using contract wallets as the base account. A contract wallet doesn't have a PK so the account can't sign a message with any underlying key. If a contract account wanted to publish a PK, it would have to be one it generated.

> Yea that seems like a good architecture. Perhaps we should rename this repo to umbra-protocol and create a separate repo for the app itself to move these issues into. And then once we decide on a key-management approach add some helper functions to this repo.

Agreed.

> I think we should try to avoid users needing a separate mnemonic just for Umbra, and that we'd want to support something like MetaMask integration, where they already have a single seed phrase backed up, and just use a new, separate keypair for Umbra

I agree having to manage a separate mnemonic is not ideal, but I'm also not sure of the capabilities of a MetaMask integration to share key material. My gut tells me it wouldn't be permitted, in which case we'd be requiring users to reveal & copy paste private keys, which is also bad UX and risky.

I also wonder how much users will like having to have a separate account for Umbra. Would we require them to register and point an ENS domain just at this account? Or would we let them use their existing account w/ ENS name, but generate an extra account solely for creating the key material, in which case the user would have to know/remember never to use that account for anything else, or if they did it's a little weaker security because of Umbra.

At some point, we'll want to build a frontend that lets the user set up their Umbra account. One of the functions in this could be to generate a new private key, encrypt it with pbkdf, and have the user download a file backup of this as well. Tornado cash does something similar with your zkProofs.

> I once used this article to recover my seed phrase manually, which gives some insight into how MetaMask stores your seed phrase

Nice thanks for sharing, digging into it a bit, they're doing what I suspected. This package `browser-passworder` uses pbkdf2 to salt & encrypt the data and store it in local storage. When we build a front end, we should consider just using this package.

https://github.com/danfinlay/browser-passworder/blob/master/index.js#L91

**Comment by mds1** [comment]
> This package browser-passworder uses pbkdf2 to salt & encrypt the data and store it in local storage. When we build a front end, we should consider just using this package.

This is the currently implemented approach. At some point we need to determine if this is secure enough, or if we should move to an alternative solution, such as MetaMask app keys or something else entirely

**Comment by TomAFrench** [comment]
Have you considered generating the Umbra key pair using a signature from Metamask in a similar way to how Loopring handles this? This way users wouldn't have to maintain their own copy of the Umbra private key as it could be regenerated as needed.

Obviously this throws up a couple of difficulties for smart contract wallets.

**Comment by mds1** [comment]
Thanks for the suggestion @TomAFrench! We actually do plan on switching to an approach similar to the one used by Loopring, though we haven't yet worked out details of the implementation.

**Comment by mds1** [comment]
Closing because this is outdated and we'll create a new issue to track the plan for key management
