### ISSUE TITLE
Use PoW As A Spam Prevention Measure For Sends

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#50]
## Problem

Because all receivers must examine and attempt to decrypt all payment announcements published on chain, it's important to prevent spamming of the announcement contract. A malicious user, by simply sending many payments to himself, could force every other user to spend significant time/computational cycles wading through junk transactions.

Our current approach to discouraging this is to charge a negligible fee for each payment, making spamming the contract costly (even for a miner, who could avoid paying gas fees).

## Solution

An additional measure worth considering is a Proof-of-Work, validated on chain, at the time a payment is made. Umbra could require some computational expenditure to publish a payment, one that is small enough to be unnoticeably calculated by the sender's client in the normal case, but which would slow down a user with bad intent.

## Implementation

An additional `_nonce` parameter could be added to the [send methods](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts/contracts/Umbra.sol#L106). Inside each send method, the nonce can be concatenated with some portion of the cyphertext, i.e. `_ct0`, and the keccak256 hash of the combination can be calculated. The contract can then require that the resulting hash is below a threshold value.

## Questions / Considerations

* Gas – The addition of another parameter to the send methods, along with the concatenation operation, hash operation, and validity check, will all add gas costs to an Umbra send. How much, and is it worth it, especially with gas prices being high.
* How do we set the proof-of-work threshold value?
  * Static value (Just pick a reasonably low value, and hardcode it)
     * Pros: Avoids additional complications.
     * Cons: As time goes on, and hardware gets better, we get less and less protection.In the face of an active spam attack from an attacker who demonstrates the capability to generate many PoWs quickly, the protocol has no resilience.
  * Admin key updatable static value
    * Pros: Still relatively simple. Gives us the ability to adjust as hardware advances, or in the face of active spam attacks.
    * Cons: Point of centralization and security risk. Malicious or compromised Admin key could jack up the threshold, making further payments impossible (essentially the same risk exists for the fee).
  * Auto adjusting (Define an algorithm that modifies the difficulty automatically)
    * Pros: Flexible in the face of an attack, or improving hardware, but also autonomous, without centralizing intervention.
    * Cons: Complex! How would it work? Target a maximum number of payments per block? Also, might provide an attack vector in and of itself— a malicious actor with hardware could jack up the difficulty and make it hard for normal users to submit a payment.

**Comment by seresistvanandras** [comment]
I would oppose this. This just makes usage more cumbersome for legitimate users with added complexity. More importantly, it does not effectively prevent potent adversaries to spam the network with stealth transactions. The real solution would be to find an efficient way to screen for incoming stealth transactions.

This is a closely related issue to #54 . Neither of these is an issue in practice if we assume an off-chain communication line between sender and receiver. If such an information exchange exists, then it is trivial to efficiently find the stealth transaction and then none of these rate-limiting solutions are required. For instance, this is the case in a merchant-customer relationship. A customer would send the transaction hash or the final stealth address to the merchant anyway.
If such an off-chain connection does not exist, then we have a screening problem and not a rate-limiting problem. As far as I can tell, the screening problem is a quite difficult one.

**Comment by mds1** [comment]
Closing this issue, as we agree this is pretty complex with minimal benefits
