### ISSUE TITLE
Address Error Message Overlaps With Pub Key Check Box on Send Page in Advanced Mode 

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#500]
When on the send page, if you activate advanced mode (which shows the public key send check box) and enter an invalid address, the error message gets displayed overtop the checkbox. It should display above or below the checkbox instead.

<img width="579" alt="Screen Shot 2023-04-25 at 11 33 46 PM" src="https://user-images.githubusercontent.com/1479802/234466964-d344740f-b77e-44d2-8145-b3321bd90dd2.png">

**Comment by alexkeating** [comment]
#543 May fix this as well
