### ISSUE TITLE
Show the block difference between the latest fetched announcement vs. the latest mined block

### ISSUE THREAD

**Issue by garyghayrat** [ScopeLift/umbra-protocol#632]
This is so when users don't see their funds in the receive page, they can troubleshoot based on a message like "Latest fetched announcements is 5 blocks behind the latest mined block," and know that the announcements from the block where they sent their funds aren't yet fetched. It is also a way for us to troubleshoot why some users report it taking hours for them to see the funds they sent to show up on the receive page.

**Comment by jferas** [comment]
After some discussion .. going to add blocktimes to shown information to give more troubleshooting info.
