### ISSUE TITLE
App reports no compatible wallet when multiple extensions are installed

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#664]
Reported by a user: it seems when MetaMask and Rabby are both installed, the app reports there is no compatible wallet available.

![IMAGE 2024-04-22 11:10:47](https://github.com/ScopeLift/umbra-protocol/assets/1479802/b059c996-8da2-4048-92bd-867598050ced)

We should:

1. Confirm that the app is working fine with both MM & Rabby when installed independently
2. Try to reproduce the error when both extensions are installed.
3. See if upgrading our blocknative version helps
4. Investigate other possible solutions if not

**Comment by garyghayrat** [comment]
Was able to solve this issue by updating `web3-onboard`. If the problem reoccurs in the future please also reference https://onboard.blocknative.com/docs/resources/troubleshooting#where-s-my-wallet-injected-browser-extension
