### ISSUE TITLE
Investigate the OZ Signed TX implementation and whether we should use it for meta withdrawal

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#73]
What edge cases does this handle vs. a simple ECRecover call, and do we need to worry about them, or will we just incur a gas penalty?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ecc66719bd7681ed4eb8bf406f89a7408569ba9b/contracts/cryptography/ECDSA.sol#L49-L71

**Comment by mds1** [comment]
@apbendi IIRC during the audit we decided this was not necessary for our use case, because each stealth address and signature is only used once and we don't store signatures for replay protection
