### ISSUE TITLE
Handle Special Case Tokens Safely

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#99]
Need to make sure we are appropriately accounting for the following types of tokens:

- [ ] Fee on transfer, like USDT
- [ ] Rebasing tokens, like aDAI

**Comment by mds1** [comment]
Fee tokens like USDT we can account for fairly easily. Best way to do this is probably to let the frontend handle it by calling a different method to deposit fee tokens, that way we don't need unnecessary storage reads/balance checks for tokens that don't have fees

Dynamic balances/rebase tokens like aDAI and AMPL are a lot harder to support in our current architecture, so I think the best option is to not make any changes to account for them
- Umbra with aTokens is ok, you'd just some interest earned, so probably ok to still support that in the frontend
- Umbra with AMPL can result in a lot of funds loss, so probably best to not support that and other rebase tokens in the frontend
